"""
Tests that the expected synthetic data files exist and have the correct format.
These files are gitignored and generated by data/synthetic/create_synthetic_data.py;
the conftest.py autouse fixture ensures they are present before tests run.
"""
from pathlib import Path

import pytest

_SYNTH = Path(__file__).resolve().parents[1] / "data" / "synthetic"
_BLOCKS_DIR = _SYNTH / "region_blocks"
_EXPECTED_BLOCKS = ["synth_block_A", "synth_block_B", "synth_block_C", "synth_block_D"]
_MANIFEST = _SYNTH / "block_plan" / "manifest.tsv"


@pytest.mark.parametrize("block_id", _EXPECTED_BLOCKS)
def test_raw_file_exists(block_id):
    assert (_BLOCKS_DIR / f"{block_id}.raw").exists(), (
        f"{block_id}.raw not found — run python data/synthetic/create_synthetic_data.py"
    )


def test_manifest_exists():
    assert _MANIFEST.exists(), "manifest.tsv not found"


def test_raw_header_has_plink_prefix():
    """First 6 columns of a .raw header must be FID IID PAT MAT SEX PHENOTYPE."""
    raw_path = _BLOCKS_DIR / "synth_block_A.raw"
    with open(raw_path) as fh:
        header = fh.readline().strip().split()
    assert header[:6] == ["FID", "IID", "PAT", "MAT", "SEX", "PHENOTYPE"], (
        f"Unexpected header prefix: {header[:6]}"
    )


def test_raw_file_row_count():
    """Each .raw file should have 30 data rows (30 synthetic subjects) + 1 header."""
    raw_path = _BLOCKS_DIR / "synth_block_A.raw"
    with open(raw_path) as fh:
        lines = fh.readlines()
    assert len(lines) == 31, f"Expected 31 lines (1 header + 30 subjects), got {len(lines)}"


def test_manifest_contains_expected_blocks():
    """manifest.tsv block_id column must list exactly the 4 synthetic block IDs."""
    import pandas as pd
    df = pd.read_csv(_MANIFEST, sep="\t")
    assert "block_id" in df.columns, "manifest.tsv missing 'block_id' column"
    found = set(df["block_id"].tolist())
    assert found == set(_EXPECTED_BLOCKS), (
        f"Manifest block IDs {found} != expected {set(_EXPECTED_BLOCKS)}"
    )
